'use client';

import React, { useState } from 'react';
import Link from 'next/link';
import { ArrowBigUp, ArrowBigDown, MessageSquare, ArrowRight, Verified } from 'lucide-react';
import { cn } from '@/lib/utils';

const INITIAL_POSTS = [
  {
    id: 'post1',
    title: 'Atypical presentation: 42M with crushing chest pain but normal EKG',
    author: 'cardiobros',
    tags: ['Cardiology', 'Hard'],
    excerpt: 'Patient presented with classic STEMI symptoms (crushing substernal pain radiating to jaw, diaphoresis). Initial EKG completely normal. Troponins were also negative at hour 0. What\'s your next move?',
    upvotes: 342,
    comments: 45,
    isOfficial: true,
  },
  {
    id: 'post2',
    title: 'Pediatric puzzle: 5F with 5-day fever, strawberry tongue, and rash',
    author: 'peds_resident_99',
    tags: ['Pediatrics', 'Medium'],
    excerpt: 'Mom brings in 5-year-old girl. Fever of 102F for 5 days unresponsive to Tylenol. Exam shows injected conjunctivae without exudate, cracked red lips, and a polymorphous maculopapular rash on her trunk.',
    upvotes: 184,
    comments: 22,
    isOfficial: false,
  },
  {
    id: 'post3',
    title: 'Weird lab finding: isolated elevated alkaline phosphatase in asymptomatic 60M',
    author: 'dr_house_wannabe',
    tags: ['Gastroenterology', 'Medium'],
    excerpt: 'Routine screening labs show Alk Phos 450 U/L (normal <120). AST/ALT normal. GGT is elevated. Patient feels fine, denies bone pain or jaundice. What is the most cost-effective next step in diagnosis?',
    upvotes: 89,
    comments: 14,
    isOfficial: false,
  }
];

export function CommunityFeedPreview() {
  const [posts, setPosts] = useState(INITIAL_POSTS);
  const [votedPosts, setVotedPosts] = useState<Record<string, 'up' | 'down'>>({});

  const handleVote = (postId: string, direction: 'up' | 'down') => {
    setPosts(prev => prev.map(post => {
      if (post.id === postId) {
        const currentVote = votedPosts[postId];
        let newUpvotes = post.upvotes;
        
        if (currentVote === direction) {
          // Unvote
          newUpvotes += direction === 'up' ? -1 : 1;
          setVotedPosts(prev => { const next = {...prev}; delete next[postId]; return next; });
        } else {
          // New vote or change vote
          if (currentVote) {
             newUpvotes += direction === 'up' ? 2 : -2;
          } else {
             newUpvotes += direction === 'up' ? 1 : -1;
          }
          setVotedPosts(prev => ({ ...prev, [postId]: direction }));
        }

        return { ...post, upvotes: newUpvotes };
      }
      return post;
    }));
  };

  return (
    <section id="community" className="py-24 bg-white dark:bg-[#09090B] px-6">
      <div className="max-w-6xl mx-auto">
        <div className="flex flex-col md:flex-row items-end justify-between mb-12 gap-6">
            <div className="max-w-2xl">
                <h2 className="text-3xl md:text-5xl font-extrabold text-slate-900 dark:text-white tracking-tight mb-4">
                    Community-reviewed clinical cases.
                </h2>
                <p className="text-xl font-medium text-slate-500 dark:text-slate-400">
                    Play cases generated by peers. Upvote the best ones. The highest-rated cases get permanently promoted to the official library.
                </p>
            </div>
            <Link 
              href="/app/community"
              className="px-6 py-3 bg-slate-100 hover:bg-slate-200 dark:bg-zinc-800 dark:hover:bg-zinc-700 text-slate-900 dark:text-white font-bold rounded-xl transition-colors flex items-center gap-2 shrink-0"
            >
                Browse all cases <ArrowRight className="w-4 h-4" />
            </Link>
        </div>

        <div className="grid md:grid-cols-12 gap-8">
            {/* Fake Feed */}
            <div className="md:col-span-8 flex flex-col gap-4">
                {posts.map((post) => {
                    const myVote = votedPosts[post.id];
                    
                    return (
                        <div key={post.id} className="bg-slate-50 dark:bg-[#18181B] border border-slate-200 dark:border-zinc-800 rounded-2xl p-4 flex gap-4 transition-colors hover:border-slate-300 dark:hover:border-zinc-700">
                            {/* Vote Column */}
                            <div className="flex flex-col items-center gap-1 shrink-0 pt-1">
                                <button 
                                  onClick={() => handleVote(post.id, 'up')}
                                  className={cn("p-1.5 rounded-lg transition-colors", myVote === 'up' ? "bg-emerald-100 dark:bg-emerald-500/20 text-emerald-600 dark:text-emerald-400" : "text-slate-400 hover:bg-slate-200 dark:hover:bg-zinc-800")}
                                >
                                    <ArrowBigUp className={cn("w-6 h-6", myVote === 'up' && "fill-current")} />
                                </button>
                                <span className={cn("text-sm font-bold", myVote === 'up' ? "text-emerald-600 dark:text-emerald-400" : myVote === 'down' ? "text-rose-600 dark:text-rose-400" : "text-slate-600 dark:text-slate-400")}>
                                    {post.upvotes}
                                </span>
                                <button 
                                  onClick={() => handleVote(post.id, 'down')}
                                  className={cn("p-1.5 rounded-lg transition-colors", myVote === 'down' ? "bg-rose-100 dark:bg-rose-500/20 text-rose-600 dark:text-rose-400" : "text-slate-400 hover:bg-slate-200 dark:hover:bg-zinc-800")}
                                >
                                    <ArrowBigDown className={cn("w-6 h-6", myVote === 'down' && "fill-current")} />
                                </button>
                            </div>
                            
                            {/* Content Column */}
                            <div className="flex-1 min-w-0">
                                <div className="flex items-center gap-2 mb-2 flex-wrap">
                                    <span className="text-xs font-bold text-slate-500 flex items-center gap-1">
                                        {post.isOfficial && <Verified className="w-3.5 h-3.5 text-indigo-500" />}
                                        u/{post.author}
                                    </span>
                                    <span className="text-slate-300 dark:text-zinc-600">•</span>
                                    <div className="flex gap-1.5">
                                        {post.tags.map(tag => (
                                            <span key={tag} className="px-2 py-0.5 rounded-full bg-slate-200 dark:bg-zinc-800 text-[10px] font-bold uppercase tracking-wider text-slate-600 dark:text-slate-300">
                                                {tag}
                                            </span>
                                        ))}
                                    </div>
                                </div>
                                <h3 className="text-lg font-bold text-slate-900 dark:text-white mb-2 leading-snug">
                                    {post.title}
                                </h3>
                                <p className="text-sm text-slate-600 dark:text-slate-400 mb-4 line-clamp-2 md:line-clamp-none">
                                    {post.excerpt}
                                </p>
                                <div className="flex items-center gap-4">
                                    <button className="flex items-center gap-1.5 text-xs font-bold text-slate-500 hover:text-slate-700 dark:hover:text-slate-300 transition-colors bg-slate-100 dark:bg-zinc-800/50 px-3 py-1.5 rounded-lg">
                                        <MessageSquare className="w-4 h-4" /> {post.comments} Comments
                                    </button>
                                    <span className="text-xs font-medium text-slate-400">
                                        <ArrowRight className="w-4 h-4 inline-block mr-1" />
                                        Play this case
                                    </span>
                                </div>
                            </div>
                        </div>
                    );
                })}
            </div>

            {/* Sidebar Context */}
            <div className="md:col-span-4 mt-8 md:mt-0">
                <div className="bg-indigo-50 dark:bg-indigo-500/5 border border-indigo-100 dark:border-indigo-500/10 rounded-2xl p-6 sticky top-32">
                    <h3 className="text-lg font-bold text-indigo-900 dark:text-indigo-100 mb-4">
                        How it works
                    </h3>
                    <ul className="space-y-4">
                        <li className="flex gap-3">
                            <div className="w-6 h-6 rounded bg-indigo-200 dark:bg-indigo-500/20 text-indigo-700 dark:text-indigo-300 flex items-center justify-center text-xs font-bold shrink-0 mt-0.5">1</div>
                            <p className="text-sm font-medium text-indigo-800 dark:text-indigo-200/80">Users create cases in AI Studio with custom parameters.</p>
                        </li>
                        <li className="flex gap-3">
                            <div className="w-6 h-6 rounded bg-indigo-200 dark:bg-indigo-500/20 text-indigo-700 dark:text-indigo-300 flex items-center justify-center text-xs font-bold shrink-0 mt-0.5">2</div>
                            <p className="text-sm font-medium text-indigo-800 dark:text-indigo-200/80">They publish to the Community Feed for peer review.</p>
                        </li>
                        <li className="flex gap-3">
                            <div className="w-6 h-6 rounded bg-indigo-200 dark:bg-indigo-500/20 text-indigo-700 dark:text-indigo-300 flex items-center justify-center text-xs font-bold shrink-0 mt-0.5">3</div>
                            <p className="text-sm font-medium text-indigo-800 dark:text-indigo-200/80">Cases with high upvotes and realistic mechanisms are promoted to the Official Library.</p>
                        </li>
                    </ul>
                </div>
            </div>
        </div>
      </div>
    </section>
  );
}
