'use client';

import React, { useState } from 'react';
import Link from 'next/link';
import { Stethoscope, BrainCircuit, Users, Swords, TrendingUp, ArrowRight } from 'lucide-react';
import { cn } from '@/lib/utils';
import Image from 'next/image';

const TABS = [
  {
    id: 'session',
    title: 'Session',
    icon: <Stethoscope className="w-5 h-5" />,
    color: 'text-indigo-600 dark:text-indigo-400',
    bgColor: 'bg-indigo-50 dark:bg-indigo-500/10',
    bullets: [
      'Progressive disclosure cases mimic real patient presentations.',
      'Organized by organ system to help you master specific domains.',
      'Read like a structured APK or play fast with quick vignettes.'
    ],
    cta: 'Start a Session',
    link: '/app/session?mode=daily',
    mockContent: (
      <div className="w-full h-full flex items-center justify-center p-6 bg-slate-50 dark:bg-[#18181B] rounded-2xl border border-slate-200/60 dark:border-zinc-800/80 shadow-inner">
         <div className="w-full max-w-sm bg-white dark:bg-zinc-900 rounded-xl shadow-lg border border-slate-100 dark:border-zinc-800 overflow-hidden">
             <div className="p-4 border-b border-slate-100 dark:border-zinc-800 bg-slate-50/50 dark:bg-zinc-800/50">
                <div className="h-3 w-24 bg-indigo-200 dark:bg-indigo-500/30 rounded-full mb-2" />
                <div className="h-5 w-48 bg-slate-800 dark:bg-slate-200 rounded-lg" />
             </div>
             <div className="p-4 space-y-4">
                 <div className="h-4 w-full bg-slate-100 dark:bg-zinc-800 rounded-full" />
                 <div className="h-4 w-5/6 bg-slate-100 dark:bg-zinc-800 rounded-full" />
                 <div className="h-4 w-4/6 bg-slate-100 dark:bg-zinc-800 rounded-full" />
             </div>
             <div className="p-4 bg-slate-50 dark:bg-zinc-800/30 border-t border-slate-100 dark:border-zinc-800 flex gap-2">
                 <div className="h-10 flex-1 bg-white dark:bg-zinc-800 border border-slate-200 dark:border-zinc-700 rounded-lg" />
                 <div className="h-10 w-10 bg-indigo-600 rounded-lg flex items-center justify-center text-white" />
             </div>
         </div>
      </div>
    )
  },
  {
    id: 'studio',
    title: 'AI Studio',
    icon: <BrainCircuit className="w-5 h-5" />,
    color: 'text-amber-600 dark:text-amber-500',
    bgColor: 'bg-amber-50 dark:bg-amber-500/10',
    bullets: [
      'Generate unlimited clinical scenarios with our fine-tuned AI model.',
      'Customize by difficulty, organ system, or specific disease entity.',
      'Publish your best generations to the community for review.'
    ],
    cta: 'Try AI Studio',
    link: '/app/studio',
    mockContent: (
      <div className="w-full h-full flex items-center justify-center p-6 bg-slate-50 dark:bg-[#18181B] rounded-2xl border border-slate-200/60 dark:border-zinc-800/80 shadow-inner">
         <div className="w-full max-w-sm space-y-4">
            <div className="grid grid-cols-2 gap-4">
                <div className="bg-white dark:bg-zinc-900 p-4 rounded-xl shadow-sm border border-slate-200 dark:border-zinc-800">
                    <div className="h-3 w-16 bg-slate-200 dark:bg-zinc-700 rounded-full mb-3" />
                    <div className="h-8 w-full bg-amber-50 dark:bg-amber-500/10 border border-amber-200 dark:border-amber-500/30 rounded-lg" />
                </div>
                <div className="bg-white dark:bg-zinc-900 p-4 rounded-xl shadow-sm border border-slate-200 dark:border-zinc-800">
                    <div className="h-3 w-20 bg-slate-200 dark:bg-zinc-700 rounded-full mb-3" />
                    <div className="h-8 w-full bg-slate-100 dark:bg-zinc-800 rounded-lg" />
                </div>
            </div>
            <div className="bg-white dark:bg-zinc-900 p-4 rounded-xl shadow-lg border border-slate-200 dark:border-zinc-800">
                <div className="h-3 w-16 bg-slate-200 dark:bg-zinc-700 rounded-full mb-3" />
                <div className="h-20 w-full bg-slate-100 dark:bg-zinc-800 rounded-lg mb-4" />
                <div className="h-12 w-full bg-amber-500 rounded-lg flex flex-col items-center justify-center">
                    <div className="h-2 w-1/3 bg-white/50 rounded-full mb-1.5" />
                    <div className="h-2 w-1/4 bg-white/30 rounded-full" />
                </div>
            </div>
         </div>
      </div>
    )
  },
  {
    id: 'community',
    title: 'Community',
    icon: <Users className="w-5 h-5" />,
    color: 'text-emerald-600 dark:text-emerald-500',
    bgColor: 'bg-emerald-50 dark:bg-emerald-500/10',
    bullets: [
      'A constant feed of new, challenging cases generated by peers.',
      'Upvote realistic cases and downvote hallucinations or errors.',
      'The highest-rated cases make it to the official DxLadder library.'
    ],
    cta: 'Browse Community',
    link: '/app/community',
    mockContent: (
      <div className="w-full h-full flex flex-col gap-4 p-6 bg-slate-50 dark:bg-[#18181B] rounded-2xl border border-slate-200/60 dark:border-zinc-800/80 shadow-inner overflow-hidden">
         {[1, 2].map((i) => (
            <div key={i} className="flex gap-4 bg-white dark:bg-zinc-900 p-4 rounded-xl shadow-sm border border-slate-200 dark:border-zinc-800">
                <div className="flex flex-col items-center gap-2">
                    <div className="w-6 h-6 rounded bg-emerald-100 dark:bg-emerald-500/20" />
                    <div className="h-3 w-4 bg-slate-300 dark:bg-zinc-600 rounded-full" />
                    <div className="w-6 h-6 rounded bg-slate-100 dark:bg-zinc-800" />
                </div>
                <div className="flex-1 space-y-3">
                    <div className="flex items-center gap-2">
                        <div className="h-3 w-16 bg-emerald-200 dark:bg-emerald-500/40 rounded-full" />
                        <div className="h-3 w-20 bg-slate-200 dark:bg-zinc-700 rounded-full" />
                    </div>
                    <div className="h-4 w-full bg-slate-800 dark:bg-slate-200 rounded-lg" />
                    <div className="h-3 w-3/4 bg-slate-200 dark:bg-zinc-700 rounded-full" />
                </div>
            </div>
         ))}
      </div>
    )
  },
  {
    id: 'games',
    title: 'Games',
    icon: <Swords className="w-5 h-5" />,
    color: 'text-rose-600 dark:text-rose-500',
    bgColor: 'bg-rose-50 dark:bg-rose-500/10',
    bullets: [
      'Climb the global ranked ladder in 1v1 Dx Duels.',
      'Open Private Arenas to challenge your friends securely.',
      'Experience novel modes like Clue Auction and Chaos Mode.'
    ],
    cta: 'Play Games',
    link: '/app/games',
    mockContent: (
      <div className="w-full h-full flex items-center justify-center p-6 bg-slate-50 dark:bg-[#18181B] rounded-2xl border border-slate-200/60 dark:border-zinc-800/80 shadow-inner">
         <div className="w-full max-w-sm bg-white dark:bg-zinc-900 rounded-xl shadow-lg border border-slate-200 dark:border-zinc-800 overflow-hidden flex flex-col items-center justify-center p-8 text-center relative">
             <div className="absolute top-4 left-4 h-4 w-16 bg-amber-200 dark:bg-amber-500/30 rounded-full" />
             <div className="w-16 h-16 rounded-2xl bg-gradient-to-br from-rose-500 to-orange-500 flex items-center justify-center mb-6 shadow-lg shadow-rose-500/30">
                 <Swords className="w-8 h-8 text-white" />
             </div>
             <div className="h-6 w-3/4 bg-slate-800 dark:bg-slate-200 rounded-lg mb-4" />
             <div className="h-3 w-1/2 bg-slate-300 dark:bg-zinc-600 rounded-full mb-8" />
             <div className="w-full h-12 bg-slate-900 dark:bg-white rounded-xl mb-3 flex items-center justify-center" />
             <div className="w-full h-12 bg-slate-100 dark:bg-zinc-800 rounded-xl border border-slate-200 dark:border-zinc-700" />
         </div>
      </div>
    )
  },
  {
    id: 'progress',
    title: 'Progress',
    icon: <TrendingUp className="w-5 h-5" />,
    color: 'text-cyan-600 dark:text-cyan-500',
    bgColor: 'bg-cyan-50 dark:bg-cyan-500/10',
    bullets: [
      'Track your transition from "Solved" to "Mastered".',
      'The Mechanism Round ensures you understand the "why", not just the "what".',
      'Visualize your strengths and weaknesses across all medical domains.'
    ],
    cta: 'View Progress',
    link: '/app/progress',
    mockContent: (
      <div className="w-full h-full flex items-center justify-center p-6 bg-slate-50 dark:bg-[#18181B] rounded-2xl border border-slate-200/60 dark:border-zinc-800/80 shadow-inner">
         <div className="w-full max-w-sm space-y-4">
            <div className="bg-white dark:bg-zinc-900 p-5 rounded-xl shadow-lg border border-slate-200 dark:border-zinc-800">
                <div className="flex items-center justify-between mb-6">
                    <div className="h-4 w-24 bg-slate-800 dark:bg-slate-200 rounded-lg" />
                    <div className="h-6 w-12 bg-cyan-100 dark:bg-cyan-500/20 rounded-full" />
                </div>
                <div className="flex items-end justify-between h-24 gap-2">
                    {[40, 70, 45, 90, 60, 80, 50].map((h, i) => (
                        <div key={i} className="w-full bg-cyan-500/20 dark:bg-cyan-500/10 rounded-t-sm relative">
                            <div className="absolute bottom-0 w-full bg-cyan-500 rounded-t-sm" style={{ height: `${h}%` }} />
                        </div>
                    ))}
                </div>
            </div>
            <div className="bg-white dark:bg-zinc-900 p-4 rounded-xl shadow-sm border border-slate-200 dark:border-zinc-800 flex items-center gap-4">
                <div className="w-12 h-12 rounded-full border-4 border-emerald-500/30 flex items-center justify-center">
                    <div className="w-9 h-9 rounded-full bg-emerald-500 flex items-center justify-center text-[10px] text-white font-bold">85%</div>
                </div>
                <div>
                   <div className="h-4 w-24 bg-slate-800 dark:bg-slate-200 rounded-lg mb-2" />
                   <div className="h-3 w-32 bg-slate-300 dark:bg-zinc-600 rounded-full" />
                </div>
            </div>
         </div>
      </div>
    )
  }
];

export function ProductTabs() {
  const [activeTab, setActiveTab] = useState(TABS[0].id);
  const activeData = TABS.find(t => t.id === activeTab) || TABS[0];

  return (
    <section id="product" className="py-24 md:py-32 px-6">
      <div className="max-w-6xl mx-auto">
        <div className="text-center mb-16">
          <h2 className="text-3xl md:text-5xl font-extrabold text-slate-900 dark:text-white tracking-tight mb-4">
            Everything you need to master diagnosis.
          </h2>
          <p className="text-xl font-medium text-slate-500 dark:text-slate-400 max-w-2xl mx-auto">
            A complete ecosystem for clinical reasoning—from focused daily practice to viral multiplayer games.
          </p>
        </div>

        <div className="grid md:grid-cols-12 gap-12 items-start">
          
          {/* Left: Tabs List */}
          <div className="md:col-span-5 flex flex-col gap-2">
            {TABS.map((tab) => {
              const isActive = activeTab === tab.id;
              return (
                <button
                  key={tab.id}
                  onClick={() => setActiveTab(tab.id)}
                  className={cn(
                    "flex flex-col text-left p-5 rounded-2xl transition-all duration-300 border-2",
                    isActive 
                      ? "bg-white dark:bg-[#18181B] border-indigo-500/20 dark:border-indigo-500/30 shadow-[0_8px_30px_rgb(0,0,0,0.04)]" 
                      : "bg-transparent border-transparent hover:bg-slate-50 dark:hover:bg-zinc-900/50"
                  )}
                >
                  <div className="flex items-center gap-4 mb-1">
                    <div className={cn("p-2 rounded-xl transition-colors", isActive ? tab.bgColor : "bg-slate-100 dark:bg-zinc-800")}>
                      <div className={isActive ? tab.color : "text-slate-400 dark:text-slate-500"}>
                        {tab.icon}
                      </div>
                    </div>
                    <h3 className={cn("text-xl font-bold", isActive ? "text-slate-900 dark:text-white" : "text-slate-600 dark:text-slate-400")}>
                      {tab.title}
                    </h3>
                  </div>
                  
                  {/* Expanded Content (CSS transition height) */}
                  <div className={cn(
                    "overflow-hidden transition-all duration-300 ease-in-out",
                    isActive ? "max-h-96 opacity-100 mt-4" : "max-h-0 opacity-0"
                  )}>
                    <ul className="space-y-3 mb-6">
                      {tab.bullets.map((bullet, i) => (
                        <li key={i} className="flex items-start gap-2 text-slate-600 dark:text-slate-400 font-medium">
                          <span className={cn("mt-1.5 w-1.5 h-1.5 rounded-full shrink-0", tab.bgColor.replace('/10', ''))} />
                          {bullet}
                        </li>
                      ))}
                    </ul>
                    <Link 
                      href={tab.link}
                      className={cn(
                        "inline-flex items-center gap-2 font-bold transition-colors",
                        tab.color
                      )}
                    >
                      {tab.cta} <ArrowRight className="w-4 h-4" />
                    </Link>
                  </div>
                </button>
              );
            })}
          </div>

          {/* Right: Mock Panel Window */}
          <div className="md:col-span-7 sticky top-32">
            <div className="aspect-[4/3] md:aspect-video rounded-3xl overflow-hidden relative bg-slate-100 dark:bg-zinc-900 border border-slate-200/60 dark:border-zinc-800/80 shadow-2xl">
               {/* Browser Chrome */}
               <div className="absolute top-0 inset-x-0 h-12 bg-white/50 dark:bg-zinc-900/50 backdrop-blur-md border-b border-slate-200/60 dark:border-zinc-800/60 flex items-center px-4 gap-2 z-10">
                  <div className="w-3 h-3 rounded-full bg-slate-300 dark:bg-zinc-700" />
                  <div className="w-3 h-3 rounded-full bg-slate-300 dark:bg-zinc-700" />
                  <div className="w-3 h-3 rounded-full bg-slate-300 dark:bg-zinc-700" />
                  <div className="ml-4 h-6 w-1/3 bg-slate-200/50 dark:bg-zinc-800/50 rounded-md" />
               </div>
               
               {/* Content Area with smooth crossfade */}
               <div className="pt-12 w-full h-full relative">
                  {TABS.map((tab) => (
                    <div 
                      key={tab.id}
                      className={cn(
                        "absolute inset-0 pt-12 transition-all duration-500 ease-in-out",
                        activeTab === tab.id ? "opacity-100 scale-100 pointer-events-auto" : "opacity-0 scale-95 pointer-events-none"
                      )}
                    >
                      {tab.mockContent}
                    </div>
                  ))}
               </div>
            </div>
          </div>

        </div>
      </div>
    </section>
  );
}
